// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddAccountBalance(ctx context.Context, arg AddAccountBalanceParams) (Account, error)
	CountAccounts(ctx context.Context) (int64, error)
	CountEntries(ctx context.Context) (int64, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAccount(ctx context.Context, id int64) error
	GetAccount(ctx context.Context, id int64) (Account, error)
	GetAccountForUpdate(ctx context.Context, id int64) (Account, error)
	GetEntry(ctx context.Context, id int64) (Entry, error)
	GetFirstAccount(ctx context.Context) (Account, error)
	GetFirstEntry(ctx context.Context) (Entry, error)
	GetFirstTransfer(ctx context.Context) (Transfer, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetTransfer(ctx context.Context, id int64) (Transfer, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListAccount(ctx context.Context, arg ListAccountParams) ([]Account, error)
	ListEntryByAccountId(ctx context.Context, arg ListEntryByAccountIdParams) ([]Entry, error)
	ListTransferByFromId(ctx context.Context, arg ListTransferByFromIdParams) ([]Transfer, error)
	ListTransferByFromIdAndToId(ctx context.Context, arg ListTransferByFromIdAndToIdParams) ([]Transfer, error)
	ListTransferByToId(ctx context.Context, arg ListTransferByToIdParams) ([]Transfer, error)
	UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) (Account, error)
}

var _ Querier = (*Queries)(nil)
