apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - groups:
      - system:masters
      userarn: arn:aws:iam::603855862913:user/github-ci
      username: github-ci