# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Run unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest

  services:
    postgres:
      image: postgres:latest
      env:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: 123456
        POSTGRES_DB: simple-bank
      ports:
        - 5432:5432
      # 符号>-是YAML语法中的一种表示多行字符串的方式，它的意思是将后面的多行文本合并为一行，并用空格分隔，同时去掉末尾的换行符。
      options: >- 
        --health-cmd pg_isready
        --health-interval 10s
        --health-timeout 5s
        --health-retries 5

  steps:
  - name: Check out code into the Go module directory
    uses: actions/checkout@v3

  - name: Set up Go
    uses: actions/setup-go@v3
    with:
      go-version: 1.18

  - name: Install golang-migrate
    run: |
      curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-amd64.tar.gz | tar xvz
      sudo mv migrate /usr/bin
      which migrate

  - name: Run migrations
    run: make migrateup

  - name: Test
    run: make test